// Static curated company data for interview preparation
const companies = [
  {
    id: 'google',
    name: 'Google',
    logo: 'https://logo.clearbit.com/google.com',
    industry: 'Technology',
    difficulty: 'Hard',
    description: 'Google is known for its rigorous technical interviews focusing on algorithms, data structures, and system design. Expect multiple rounds including phone screens and on-site interviews.',
    interviewProcess: [
      { step: 1, title: 'Online Application', description: 'Submit resume and complete initial screening' },
      { step: 2, title: 'Recruiter Call', description: '30-min call to discuss background and role fit' },
      { step: 3, title: 'Phone Screen', description: '45-min technical coding interview via Google Meet' },
      { step: 4, title: 'On-site Interviews', description: '4-5 rounds covering coding, system design, and behavioral' },
      { step: 5, title: 'Hiring Committee', description: 'Committee review of all interview feedback' },
    ],
    commonTopics: ['Arrays & Strings', 'Trees & Graphs', 'Dynamic Programming', 'System Design', 'Behavioral (Googleyness)'],
    sampleQuestions: [
      { question: 'Design a URL shortening service like bit.ly', category: 'System Design', difficulty: 'Hard' },
      { question: 'Find the longest substring without repeating characters', category: 'Coding', difficulty: 'Medium' },
      { question: 'Implement an LRU Cache', category: 'Coding', difficulty: 'Medium' },
      { question: 'Tell me about a time you had to deal with ambiguity', category: 'Behavioral', difficulty: 'Medium' },
      { question: 'Design Google Search autocomplete', category: 'System Design', difficulty: 'Hard' },
      { question: 'Merge K sorted linked lists', category: 'Coding', difficulty: 'Hard' },
    ],
  },
  {
    id: 'amazon',
    name: 'Amazon',
    logo: 'https://logo.clearbit.com/amazon.com',
    industry: 'Technology / E-Commerce',
    difficulty: 'Hard',
    description: 'Amazon interviews are heavily centered around their 16 Leadership Principles. Expect a strong focus on behavioral questions alongside technical problem-solving and system design.',
    interviewProcess: [
      { step: 1, title: 'Online Assessment', description: 'Coding challenges and work simulation on HackerRank' },
      { step: 2, title: 'Phone Interview', description: '1-hour technical + behavioral interview' },
      { step: 3, title: 'On-site Loop', description: '4-5 rounds with a Bar Raiser interview' },
      { step: 4, title: 'Debrief', description: 'Interviewers meet to discuss and make hiring decision' },
    ],
    commonTopics: ['Leadership Principles', 'Arrays & Hash Maps', 'Trees & Graphs', 'System Design', 'Object-Oriented Design'],
    sampleQuestions: [
      { question: 'Design an e-commerce order processing system', category: 'System Design', difficulty: 'Hard' },
      { question: 'Tell me about a time you disagreed with your manager', category: 'Behavioral', difficulty: 'Medium' },
      { question: 'Find two numbers that add up to a target (Two Sum)', category: 'Coding', difficulty: 'Easy' },
      { question: 'Implement a min stack with O(1) getMin', category: 'Coding', difficulty: 'Medium' },
      { question: 'Tell me about a time you took ownership of a project', category: 'Behavioral', difficulty: 'Medium' },
      { question: 'Design a parking lot system', category: 'System Design', difficulty: 'Medium' },
    ],
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    logo: 'https://logo.clearbit.com/microsoft.com',
    industry: 'Technology',
    difficulty: 'Hard',
    description: 'Microsoft interviews focus on coding fundamentals, system design, and cultural fit. The process is thorough but generally considered more collaborative than adversarial.',
    interviewProcess: [
      { step: 1, title: 'Resume Screen', description: 'Recruiter reviews your background and experience' },
      { step: 2, title: 'Phone Screen', description: '30-45 min technical interview with a team member' },
      { step: 3, title: 'On-site Interviews', description: '4-5 rounds of technical and behavioral interviews' },
      { step: 4, title: 'As-Appropriate', description: 'Final interview with a senior hire manager' },
    ],
    commonTopics: ['Data Structures', 'Algorithms', 'System Design', 'Object-Oriented Design', 'Behavioral'],
    sampleQuestions: [
      { question: 'Design a file synchronization service like OneDrive', category: 'System Design', difficulty: 'Hard' },
      { question: 'Reverse a linked list', category: 'Coding', difficulty: 'Easy' },
      { question: 'Find the median of two sorted arrays', category: 'Coding', difficulty: 'Hard' },
      { question: 'How would you design an elevator system?', category: 'System Design', difficulty: 'Medium' },
      { question: 'Describe a challenging project and how you overcame obstacles', category: 'Behavioral', difficulty: 'Medium' },
    ],
  },
  {
    id: 'meta',
    name: 'Meta',
    logo: 'https://logo.clearbit.com/meta.com',
    industry: 'Technology / Social Media',
    difficulty: 'Hard',
    description: 'Meta (Facebook) interviews are coding-heavy with a strong emphasis on speed and optimization. System design rounds are critical for senior roles.',
    interviewProcess: [
      { step: 1, title: 'Recruiter Screen', description: 'Initial call to discuss your background' },
      { step: 2, title: 'Technical Screen', description: '45-min coding interview via CoderPad' },
      { step: 3, title: 'On-site (Virtual)', description: '2 coding + 1 system design + 1 behavioral round' },
      { step: 4, title: 'Hiring Committee', description: 'Review and level determination' },
    ],
    commonTopics: ['Arrays & Strings', 'Graphs & BFS/DFS', 'Dynamic Programming', 'System Design', 'Product Sense'],
    sampleQuestions: [
      { question: 'Design Facebook News Feed', category: 'System Design', difficulty: 'Hard' },
      { question: 'Validate a binary search tree', category: 'Coding', difficulty: 'Medium' },
      { question: 'Serialize and deserialize a binary tree', category: 'Coding', difficulty: 'Hard' },
      { question: 'How would you improve Instagram Stories?', category: 'Product', difficulty: 'Medium' },
      { question: 'Find all permutations of a string', category: 'Coding', difficulty: 'Medium' },
    ],
  },
  {
    id: 'apple',
    name: 'Apple',
    logo: 'https://logo.clearbit.com/apple.com',
    industry: 'Technology / Consumer Electronics',
    difficulty: 'Hard',
    description: 'Apple interviews are known for secrecy and depth. Expect strong focus on fundamentals, attention to detail, and passion for Apple products.',
    interviewProcess: [
      { step: 1, title: 'Recruiter Call', description: 'Phone screen to assess fit and interest' },
      { step: 2, title: 'Technical Phone Screen', description: '1-hour coding interview focused on fundamentals' },
      { step: 3, title: 'On-site Interviews', description: '5-6 rounds with different team members' },
      { step: 4, title: 'Team Match', description: 'Final alignment with the hiring team' },
    ],
    commonTopics: ['Data Structures', 'Algorithms', 'Operating Systems', 'Concurrency', 'System Design'],
    sampleQuestions: [
      { question: 'Implement a thread-safe singleton pattern', category: 'Coding', difficulty: 'Medium' },
      { question: 'Design iCloud photo storage system', category: 'System Design', difficulty: 'Hard' },
      { question: 'Explain how ARC (Automatic Reference Counting) works', category: 'Concepts', difficulty: 'Medium' },
      { question: 'What is your favorite Apple product and why?', category: 'Behavioral', difficulty: 'Easy' },
      { question: 'Flatten a nested list iterator', category: 'Coding', difficulty: 'Medium' },
    ],
  },
  {
    id: 'netflix',
    name: 'Netflix',
    logo: 'https://logo.clearbit.com/netflix.com',
    industry: 'Technology / Entertainment',
    difficulty: 'Hard',
    description: 'Netflix values cultural fit heavily (Freedom & Responsibility). Technical interviews focus on real-world problems and system design at scale.',
    interviewProcess: [
      { step: 1, title: 'Recruiter Screen', description: 'Cultural fit assessment and role discussion' },
      { step: 2, title: 'Technical Phone Screen', description: 'Deep dive into past experience and coding' },
      { step: 3, title: 'On-site Interviews', description: '4-5 rounds mixing technical and cultural interviews' },
      { step: 4, title: 'Offer & Compensation', description: 'Unique compensation discussion (all cash, no vesting)' },
    ],
    commonTopics: ['System Design', 'Microservices', 'Distributed Systems', 'Data Streaming', 'Culture Fit'],
    sampleQuestions: [
      { question: 'Design a video streaming platform like Netflix', category: 'System Design', difficulty: 'Hard' },
      { question: 'How would you handle content recommendation at scale?', category: 'System Design', difficulty: 'Hard' },
      { question: 'Tell me about a time you made a tough decision without consensus', category: 'Behavioral', difficulty: 'Medium' },
      { question: 'Implement a rate limiter', category: 'Coding', difficulty: 'Medium' },
    ],
  },
  {
    id: 'uber',
    name: 'Uber',
    logo: 'https://logo.clearbit.com/uber.com',
    industry: 'Technology / Transportation',
    difficulty: 'Hard',
    description: 'Uber interviews focus on real-time systems, geospatial problems, and large-scale distributed architectures. Strong coding fundamentals are essential.',
    interviewProcess: [
      { step: 1, title: 'Recruiter Call', description: 'Initial screening and role alignment' },
      { step: 2, title: 'Technical Phone Screen', description: '60-min coding interview' },
      { step: 3, title: 'On-site Loop', description: '4 rounds: 2 coding, 1 system design, 1 behavioral' },
    ],
    commonTopics: ['Graphs', 'Geospatial Algorithms', 'System Design', 'Real-time Systems', 'Dynamic Programming'],
    sampleQuestions: [
      { question: 'Design a ride-matching system', category: 'System Design', difficulty: 'Hard' },
      { question: 'Find the nearest drivers to a rider given GPS coordinates', category: 'Coding', difficulty: 'Medium' },
      { question: 'Implement a priority queue', category: 'Coding', difficulty: 'Medium' },
      { question: 'Design a surge pricing algorithm', category: 'System Design', difficulty: 'Hard' },
    ],
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    logo: 'https://logo.clearbit.com/x.com',
    industry: 'Technology / Social Media',
    difficulty: 'Medium',
    description: 'X (formerly Twitter) interviews cover algorithms, distributed systems, and real-time data processing. Focus on scalability and handling high-throughput systems.',
    interviewProcess: [
      { step: 1, title: 'Recruiter Screen', description: 'Background and interest assessment' },
      { step: 2, title: 'Technical Phone Screen', description: '45-min coding interview' },
      { step: 3, title: 'On-site Interviews', description: '4-5 rounds with team members' },
    ],
    commonTopics: ['Hash Maps', 'Queues & Streams', 'System Design', 'API Design', 'Real-time Processing'],
    sampleQuestions: [
      { question: 'Design a real-time tweet timeline', category: 'System Design', difficulty: 'Hard' },
      { question: 'Implement a trending topics algorithm', category: 'Coding', difficulty: 'Medium' },
      { question: 'Design a URL shortener with analytics', category: 'System Design', difficulty: 'Medium' },
      { question: 'Count the frequency of words in a stream', category: 'Coding', difficulty: 'Easy' },
    ],
  },
  {
    id: 'adobe',
    name: 'Adobe',
    logo: 'https://logo.clearbit.com/adobe.com',
    industry: 'Technology / Creative Software',
    difficulty: 'Medium',
    description: 'Adobe interviews balance coding skills with creativity and product thinking. Expect questions on data structures, algorithms, and design patterns.',
    interviewProcess: [
      { step: 1, title: 'Online Assessment', description: 'HackerRank coding test (2-3 problems)' },
      { step: 2, title: 'Technical Interviews', description: '2-3 rounds of technical interviews' },
      { step: 3, title: 'Hiring Manager Round', description: 'Behavioral and team fit discussion' },
    ],
    commonTopics: ['Arrays & Strings', 'OOP & Design Patterns', 'Trees', 'Dynamic Programming', 'Behavioral'],
    sampleQuestions: [
      { question: 'Implement a basic text editor with undo/redo', category: 'Coding', difficulty: 'Medium' },
      { question: 'Design a collaborative document editing system', category: 'System Design', difficulty: 'Hard' },
      { question: 'Find the longest palindromic substring', category: 'Coding', difficulty: 'Medium' },
      { question: 'Explain the Observer design pattern', category: 'Concepts', difficulty: 'Easy' },
    ],
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    logo: 'https://logo.clearbit.com/salesforce.com',
    industry: 'Technology / CRM',
    difficulty: 'Medium',
    description: 'Salesforce interviews emphasize coding, system design, and alignment with their core values (Trust, Customer Success, Innovation, Equality).',
    interviewProcess: [
      { step: 1, title: 'Recruiter Screen', description: 'Initial discussion about role and experience' },
      { step: 2, title: 'Technical Screen', description: 'Coding interview via HackerRank or phone' },
      { step: 3, title: 'On-site Loop', description: '3-4 rounds of technical and values-based interviews' },
    ],
    commonTopics: ['Data Structures', 'API Design', 'Cloud Architecture', 'Behavioral', 'System Design'],
    sampleQuestions: [
      { question: 'Design a multi-tenant CRM system', category: 'System Design', difficulty: 'Hard' },
      { question: 'Implement a trie for autocomplete', category: 'Coding', difficulty: 'Medium' },
      { question: 'How do you handle conflicting priorities?', category: 'Behavioral', difficulty: 'Easy' },
      { question: 'Design a notification delivery system', category: 'System Design', difficulty: 'Medium' },
    ],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    logo: 'https://logo.clearbit.com/stripe.com',
    industry: 'Technology / Fintech',
    difficulty: 'Hard',
    description: 'Stripe interviews are unique — they focus on practical coding (building real features) rather than algorithmic puzzles. Expect API design and debugging challenges.',
    interviewProcess: [
      { step: 1, title: 'Recruiter Call', description: 'Role fit and background discussion' },
      { step: 2, title: 'Phone Interview', description: 'Practical coding challenge (build a feature)' },
      { step: 3, title: 'On-site Interviews', description: '4 rounds: bug squash, integration, design, and manager' },
    ],
    commonTopics: ['API Design', 'Payment Systems', 'Debugging', 'System Design', 'Practical Coding'],
    sampleQuestions: [
      { question: 'Design a payment processing pipeline', category: 'System Design', difficulty: 'Hard' },
      { question: 'Build a basic API rate limiter', category: 'Coding', difficulty: 'Medium' },
      { question: 'Debug a broken webhook delivery system', category: 'Debugging', difficulty: 'Medium' },
      { question: 'Design an idempotent payment API', category: 'System Design', difficulty: 'Hard' },
    ],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    logo: 'https://logo.clearbit.com/linkedin.com',
    industry: 'Technology / Professional Network',
    difficulty: 'Medium',
    description: 'LinkedIn interviews follow a structured process similar to other large tech companies. Focus on data structures, algorithms, and system design with strong behavioral components.',
    interviewProcess: [
      { step: 1, title: 'Recruiter Screen', description: 'Phone call to discuss role and experience' },
      { step: 2, title: 'Phone Interviews', description: '2 phone screens (1 coding + 1 design)' },
      { step: 3, title: 'On-site Loop', description: '4 rounds: coding, system design, and behavioral' },
    ],
    commonTopics: ['Graphs & Networks', 'Search Algorithms', 'System Design', 'Data Modeling', 'Behavioral'],
    sampleQuestions: [
      { question: 'Design LinkedIn connection recommendations', category: 'System Design', difficulty: 'Hard' },
      { question: 'Find the shortest path between two users in a social graph', category: 'Coding', difficulty: 'Medium' },
      { question: 'Design a messaging system', category: 'System Design', difficulty: 'Medium' },
      { question: 'Implement a feed ranking algorithm', category: 'Coding', difficulty: 'Hard' },
    ],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    logo: 'https://logo.clearbit.com/spotify.com',
    industry: 'Technology / Music Streaming',
    difficulty: 'Medium',
    description: 'Spotify values collaborative problem-solving and cultural fit. Technical interviews cover algorithms, system design, and domain-specific challenges in media streaming.',
    interviewProcess: [
      { step: 1, title: 'Recruiter Screen', description: 'Background review and role alignment' },
      { step: 2, title: 'Technical Screen', description: 'Coding challenge via online platform' },
      { step: 3, title: 'On-site Interviews', description: '3-4 rounds including system design and cultural' },
    ],
    commonTopics: ['Data Structures', 'Recommendation Systems', 'Audio Streaming', 'System Design', 'Collaboration'],
    sampleQuestions: [
      { question: 'Design a music recommendation engine', category: 'System Design', difficulty: 'Hard' },
      { question: 'Implement a shuffle algorithm that feels random', category: 'Coding', difficulty: 'Medium' },
      { question: 'Design an audio streaming service', category: 'System Design', difficulty: 'Hard' },
      { question: 'How would you handle playlist synchronization across devices?', category: 'System Design', difficulty: 'Medium' },
    ],
  },
  {
    id: 'airbnb',
    name: 'Airbnb',
    logo: 'https://logo.clearbit.com/airbnb.com',
    industry: 'Technology / Hospitality',
    difficulty: 'Hard',
    description: 'Airbnb is known for its unique interview process that heavily weighs core values alignment alongside technical skills. Expect practical coding and design challenges.',
    interviewProcess: [
      { step: 1, title: 'Recruiter Screen', description: 'Phone call about role and values alignment' },
      { step: 2, title: 'Technical Phone Screens', description: '2 coding interviews (45 min each)' },
      { step: 3, title: 'On-site Interviews', description: '5 rounds including cross-functional and values interviews' },
    ],
    commonTopics: ['Search & Filtering', 'Geospatial Systems', 'Dynamic Programming', 'System Design', 'Core Values'],
    sampleQuestions: [
      { question: 'Design an Airbnb search and booking system', category: 'System Design', difficulty: 'Hard' },
      { question: 'Implement a calendar availability checker', category: 'Coding', difficulty: 'Medium' },
      { question: 'Design a review and rating system', category: 'System Design', difficulty: 'Medium' },
      { question: 'Tell me about a time you championed belonging in your team', category: 'Behavioral', difficulty: 'Medium' },
    ],
  },
  {
    id: 'oracle',
    name: 'Oracle',
    logo: 'https://logo.clearbit.com/oracle.com',
    industry: 'Technology / Enterprise Software',
    difficulty: 'Medium',
    description: 'Oracle interviews focus on core CS fundamentals, database concepts, and Java/OOP skills. The process varies by team but generally includes coding and system design.',
    interviewProcess: [
      { step: 1, title: 'Online Assessment', description: 'Coding test on HackerRank (3-4 problems)' },
      { step: 2, title: 'Technical Interviews', description: '2-3 rounds of technical discussions' },
      { step: 3, title: 'HR Round', description: 'Behavioral and compensation discussion' },
    ],
    commonTopics: ['SQL & Databases', 'Java & OOP', 'Data Structures', 'Operating Systems', 'System Design'],
    sampleQuestions: [
      { question: 'Write a query to find the second highest salary', category: 'SQL', difficulty: 'Easy' },
      { question: 'Explain ACID properties of transactions', category: 'Concepts', difficulty: 'Easy' },
      { question: 'Design a distributed database system', category: 'System Design', difficulty: 'Hard' },
      { question: 'Implement a connection pool', category: 'Coding', difficulty: 'Medium' },
    ],
  },
  {
    id: 'flipkart',
    name: 'Flipkart',
    logo: 'https://logo.clearbit.com/flipkart.com',
    industry: 'Technology / E-Commerce',
    difficulty: 'Medium',
    description: 'Flipkart interviews are well-structured with a mix of coding, machine coding (low-level design), and system design rounds. Strong focus on problem-solving skills.',
    interviewProcess: [
      { step: 1, title: 'Online Coding Test', description: '3 coding problems on competitive programming platform' },
      { step: 2, title: 'Machine Coding Round', description: '90-min live coding round to build a small application' },
      { step: 3, title: 'Problem Solving Rounds', description: '2 rounds of DS/Algo interview' },
      { step: 4, title: 'System Design + Hiring Manager', description: 'Architecture discussion and cultural fit' },
    ],
    commonTopics: ['Arrays & Strings', 'Trees & Graphs', 'Low-Level Design', 'System Design', 'Dynamic Programming'],
    sampleQuestions: [
      { question: 'Design a shopping cart system', category: 'System Design', difficulty: 'Medium' },
      { question: 'Implement a snake and ladder game (machine coding)', category: 'Coding', difficulty: 'Medium' },
      { question: 'Find the kth largest element in an unsorted array', category: 'Coding', difficulty: 'Medium' },
      { question: 'Design a coupon/discount system for e-commerce', category: 'System Design', difficulty: 'Medium' },
    ],
  },
  {
    id: 'goldman-sachs',
    name: 'Goldman Sachs',
    logo: 'https://logo.clearbit.com/goldmansachs.com',
    industry: 'Finance / Technology',
    difficulty: 'Hard',
    description: 'Goldman Sachs interviews combine technical coding with finance domain knowledge. Expect quantitative reasoning, data structures, and leadership-focused behavioral questions.',
    interviewProcess: [
      { step: 1, title: 'Online Assessment', description: 'HackerRank test + math reasoning questions' },
      { step: 2, title: 'Video Interview', description: 'Recorded responses to behavioral questions (HireVue)' },
      { step: 3, title: 'Super Day', description: '3-5 back-to-back interviews with different teams' },
    ],
    commonTopics: ['Data Structures', 'Probability & Statistics', 'OOP', 'System Design', 'Leadership'],
    sampleQuestions: [
      { question: 'Design a stock trading platform', category: 'System Design', difficulty: 'Hard' },
      { question: 'Find the maximum profit from buying and selling stocks', category: 'Coding', difficulty: 'Easy' },
      { question: 'Calculate moving average of a data stream', category: 'Coding', difficulty: 'Easy' },
      { question: 'Why Goldman Sachs? What do you know about our engineering culture?', category: 'Behavioral', difficulty: 'Easy' },
    ],
  },
  {
    id: 'tcs',
    name: 'TCS',
    logo: 'https://logo.clearbit.com/tcs.com',
    industry: 'IT Services / Consulting',
    difficulty: 'Easy',
    description: 'TCS interviews focus on fundamental programming concepts, aptitude, and communication skills. The process is straightforward and suitable for freshers and experienced professionals.',
    interviewProcess: [
      { step: 1, title: 'TCS NQT / Online Test', description: 'Aptitude, reasoning, and coding assessment' },
      { step: 2, title: 'Technical Interview', description: 'Core CS fundamentals and project discussion' },
      { step: 3, title: 'HR Interview', description: 'Behavioral questions and offer discussion' },
    ],
    commonTopics: ['Basic Programming', 'DBMS', 'Operating Systems', 'Networking', 'OOP Concepts'],
    sampleQuestions: [
      { question: 'What is the difference between an abstract class and an interface?', category: 'Concepts', difficulty: 'Easy' },
      { question: 'Explain normalization in databases', category: 'DBMS', difficulty: 'Easy' },
      { question: 'Write a program to check if a string is a palindrome', category: 'Coding', difficulty: 'Easy' },
      { question: 'What are the pillars of OOP?', category: 'Concepts', difficulty: 'Easy' },
    ],
  },
  {
    id: 'infosys',
    name: 'Infosys',
    logo: 'https://logo.clearbit.com/infosys.com',
    industry: 'IT Services / Consulting',
    difficulty: 'Easy',
    description: 'Infosys interviews test basic programming skills, logical reasoning, and communication. The process includes online tests followed by technical and HR interviews.',
    interviewProcess: [
      { step: 1, title: 'Online Test', description: 'Aptitude, logical reasoning, and verbal ability' },
      { step: 2, title: 'Technical Interview', description: 'Programming fundamentals and project discussion' },
      { step: 3, title: 'HR Interview', description: 'Communication skills and company fit assessment' },
    ],
    commonTopics: ['C/C++ Basics', 'Data Structures', 'SQL', 'Operating Systems', 'Project Discussion'],
    sampleQuestions: [
      { question: 'What is a linked list and how does it differ from an array?', category: 'Concepts', difficulty: 'Easy' },
      { question: 'Write a SQL query to find duplicate records in a table', category: 'SQL', difficulty: 'Easy' },
      { question: 'Explain the concept of virtual memory', category: 'Concepts', difficulty: 'Easy' },
      { question: 'Tell me about a project you have worked on', category: 'Behavioral', difficulty: 'Easy' },
    ],
  },
  {
    id: 'deloitte',
    name: 'Deloitte',
    logo: 'https://logo.clearbit.com/deloitte.com',
    industry: 'Consulting / Technology',
    difficulty: 'Medium',
    description: 'Deloitte interviews focus on problem-solving, consulting skills, and technical knowledge. Expect case studies alongside traditional technical interviews.',
    interviewProcess: [
      { step: 1, title: 'Online Assessment', description: 'Aptitude, situational judgment, and coding test' },
      { step: 2, title: 'Technical Interviews', description: '1-2 rounds focused on technical skills' },
      { step: 3, title: 'Manager Interview', description: 'Case study discussion and leadership assessment' },
      { step: 4, title: 'Partner Interview', description: 'Final cultural fit and offer discussion' },
    ],
    commonTopics: ['Problem Solving', 'Cloud Technologies', 'System Design', 'Case Studies', 'Leadership'],
    sampleQuestions: [
      { question: 'Design a cloud migration strategy for a legacy banking application', category: 'System Design', difficulty: 'Hard' },
      { question: 'Explain microservices vs monolithic architecture', category: 'Concepts', difficulty: 'Medium' },
      { question: 'How would you reduce the operating costs of an IT infrastructure by 30%?', category: 'Case Study', difficulty: 'Medium' },
      { question: 'Describe a time you led a team through a challenging deliverable', category: 'Behavioral', difficulty: 'Medium' },
    ],
  },
];

export default companies;
